---
dataset:
  barriers: clokes_simp
  origin: b
  destination: h
  global_max: 2000
  global_min: 10
defaults:
  enable_3d: True
  ngen: 100 # 250
  nsegs: 100 # 100
  start: 0
  end: 1
  pop_size: 1000 #300
  cxpb: 0.5 #0.5
  mutpb: 0.1 #0.1
  max_height: 17 # 17
  max_length: null
  init_min: 1
  init_max: 2 # 2
  mut_min: 1
  mut_max: 3
  elitism: True
  dbl_tourn: False # False
  tournsize: 3 # also fitness_size 
  parsimony_size: 1.7 # range[1,2]
  fitness_first: True
  patience: null
  hof_size: 60 # 3
  seed: null # 151
  multiproc: imap #imap
  chunksize: null
validation:
  threshold: 2
  adaptive_mode: False # adaptive != no_intersect
  validation_3d: shapely
  # 3d validation options:
  # -delaunay
  # -shapely
  # -hulls_equal
  # -linprog NO
  # -triangles NO
  invalidity_cost: length*20
  intersection_cost: (intersection+1)*20
  delete_invalid: False
logging:
  no_log: False
  no_record: False
  verbose: False
visualisation:
  no_plot: False
  save_gif: False
  save_wkt: True
  short_gif: True
  map_zoom: 0.2
  sol_txt: True
  sol_png: True