---
dataset:
  barriers: example_space_simp
  origin: ex0
  destination: ex1
defaults:
  enable_3d: True
  ngen: 250 # 250
  nsegs: 100 # 100
  start: 0
  end: 1
  pop_size: 500 #300
  cxpb: 0.5 #0.5
  mutpb: 0.1 #0.1
  max_height: 17 # 17
  max_length: 200
  init_min: 1
  init_max: 5 # 2
  mut_min: 1
  mut_max: 2
  elitism: True
  dbl_tourn: False # False
  tournsize: 3 # also fitness_size 
  parsimony_size: 1.7 # range[1,2]
  fitness_first: True
  patience: null
  hof_size: 3 # 3
  seed: 151 # 151
  multiproc: imap #imap
  chunksize: None
validation:
  threshold: 2
  no_intersect: False
  validation_3d: shapely
  # 3d validation options:
  # -delaunay
  # -shapely
  # -hulls_equal
  # -linprog
  # -triangles
  # -postgis
  invalidity_cost: length*10
  intersection_cost: intersection**2
  delete_invalid: False
logging:
  no_log: False
  no_record: False
  verbose: False
visualisation:
  no_plot: False
  save_gif: False
  save_wkt: True
  short_gif: True
  map_zoom: 0.2
  sol_txt: True
  sol_png: True