dataset:
  barriers: clokes
  origin: d
  destination: h
logging:
  no_log: False
  no_record: False
  verbose: False
visualisation:
  no_plot: False
  save_gif: True
  short_gif: True
  gif_zoom: 0.15
  sol_txt: True
validation:
  threshold: 2
  no_intersect: True
  invalidity_cost: length*100
  intersection_cost: intersection**2
defaults:
  ngen: 250
  nsegs: 100
  pop_size: 300
  cxpb: 0.5
  mutpb: 0.1
  max_height: 8
  max_length: 80
  elitism: True
  patience: 100
  hof_size: 3
  seed: 151
  multiproc: imap
  chunksize: None