dataset:
  barriers: clokes
  origin: d
  destination: f
logging:
  save_log: True
  record_result: True
  verbose: False
visualisation:
  png: True
  gif: False
  short_gif: False
  gif_zoom: 0.15
  sol_txt: True
validation:
  threshold: 1.5
  no_intersect: True
  invalidity_cost: 100
  intersection_cost: 2
defaults:
  ngen: 250
  line_segments: 100
  pop_size: 300
  cxpb: 0.5
  mutpb: 0.1
  max_height: 8
  max_length: 100
  seed: 151
  multiproc: imap
  chunksize: None